### ISSUE TITLE
Add support for zlib 1.3

### ISSUE THREAD

**Issue by pmqs** [pmqs/Compress-Raw-Zlib#25]
# Tasks

- [x] Copy unchanged files from upstream -- https://github.com/madler/zlib/releases/tag/v1.3
- [x] Add changes to allow building with C++
- [x] Fix the `Z_PREFIX` symbols to make unique  (for https://github.com/pmqs/Compress-Raw-Zlib/issues/8)
- [x] Update `README` to reference the new zlib version number and date.
- [x] Update GitHub workflow files
